apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fpn15uspy-python 
  janus-idp.io/tekton: fpn15uspy-python
  backstage.io/kubernetes-id: fpn15uspy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fpn15uspy-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  